use_frameworks!

target 'APIClient-Example' do
    
    pod 'APIClient/Alamofire', :path => '../'
    
end

target 'APIClient-ExampleTests' do
    
    pod 'APIClient/Alamofire', :path => '../'
    pod 'Mockingjay'
    
end
