use_frameworks!

platform :ios, '11.0'

target 'APIClient-Example' do
    
    pod 'YALAPIClient/Alamofire', :path => '../'
    pod 'SwiftLint'
    
end

target 'APIClient-ExampleTests' do
    
    pod 'YALAPIClient/Alamofire', :path => '../'
    pod 'Mockingjay'
    
end
